[application]

[web.app]

# HTML title tag content
title = "sudoku"
base_path = "sudoku"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

# as pr. https://github.com/chmousset/rs-dioxus-deploy-action?tab=readme-ov-file#dioxus-configuration
out_dir = "target/dx/sudoku/release/web/public"
