array_width = 80
attr_fn_like_width = 80
chain_width = 80
fn_call_width = 80
fn_single_line = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
match_block_trailing_comma = false
max_width = 80
reorder_impl_items = true
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
struct_lit_width = 80
struct_variant_width = 80
tab_spaces = 2
trailing_comma = "Never"
use_small_heuristics = "Max"
where_single_line = true
wrap_comments = true
